version: 2

sources:
  - name: raw                    
    schema: raw                   
    quoting:
      database: false
      schema: false
      identifier: false
    freshness:                   
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}
    tables:
      - name: raw_listings        
        identifier: raw_listings  
        description: "Extracto RAW de Airbnb desde AB_NYC.csv."
        loaded_at_field: ingested_at
        columns:
          - name: id
            tests: [not_null]
          - name: price
            tests:
              - dbt_utils.expression_is_true:
                  expression: "price >= 0"

      - name: raw_reviews_json    
        identifier: raw_reviews_json
        description: "Eventos/Reviews en JSON."
